### ISSUE TITLE
resolution

### ISSUE THREAD

**Issue by Mizar03110** [htmltiger/esp32-ds18b20#4]
Hi, I'd like to work with highest possible resolution (12 bits I think), but I didn't found in your library how to get/set the resolution. Can you please tell me how to do that ?
Thanks, Jérôme

**Comment by htmltiger** [comment]
Its on highest 12bit by default.

to use lower res you need to modify getTemp function
see how it works
https://github.com/PaulStoffregen/OneWire/blob/386a8d0715781fd38a61c7f0a753c2f988a2abca/examples/DS18x20_Temperature/DS18x20_Temperature.ino#L98

**Comment by Mizar03110** [comment]
Ok. Thank you very much

Le jeu. 28 sept. 2023 à 12:15, htmltiger ***@***.***> a
écrit :
