### ISSUE TITLE
Long distance (not so long) issue?

### ISSUE THREAD

**Issue by skillsfactory** [htmltiger/esp32-ds18b20#7]
Hello,

I've tested your library on a breadboard with 4 sensors and 3 BUS because I've different distances.
In my real environment I can find the two closest sensors but not the two farthest (about 20 m on a single BUS).
I used an alarm BUS cable for the connections and with the original library I can reach them without particular problems, problems that I find instead on the two closest sensors, so I decided to try this other library...
Do you know the maximum distance that can be reached with this library?
Thanks
Luca

**Comment by htmltiger** [comment]
you may need stronger pullup, 4.7k is standard so if you try 2.2k or less to check if it works with longer distance

**Comment by skillsfactory** [comment]
I'll try
Thank you
